version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nestjs_postgres_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: nestjs_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nestjs_dev_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: nestjs_pgadmin_dev
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - nestjs_dev_network

volumes:
  postgres_dev_data:

networks:
  nestjs_dev_network:
    driver: bridge 